<!-- Include XLSX Library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>

<?php
// ── Convert logos to base64 data-URIs so they work in the about:blank print window ──
$logo_left_path  = __DIR__ . '/../images/logo.jpg';
$logo_right_path = __DIR__ . '/../images/logo1.png';

$logo_left_b64  = '';
$logo_right_b64 = '';

if (file_exists($logo_left_path)) {
    $logo_left_b64 = 'data:image/jpeg;base64,' . base64_encode(file_get_contents($logo_left_path));
}
if (file_exists($logo_right_path)) {
    $logo_right_b64 = 'data:image/png;base64,' . base64_encode(file_get_contents($logo_right_path));
}
?>

<script>
// ── Logo data URIs (generated by PHP) ──────────────────────────
const PRINT_LOGO_LEFT  = <?php echo json_encode($logo_left_b64); ?>;
const PRINT_LOGO_RIGHT = <?php echo json_encode($logo_right_b64); ?>;

// Export table to Excel
function exportReportToExcel(tableId, reportTitle, filename) {
    if (typeof XLSX === 'undefined') {
        alert('Loading export library, please try again...');
        return;
    }
    
    const table = document.getElementById(tableId);
    const wb = XLSX.utils.book_new();
    const data = [];
    
    // Add headers
    data.push(['PASSI CITY - DRRMO']);
    data.push([reportTitle]);
    data.push(['Generated: ' + new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })]);
    data.push([]);
    
    // Get table headers
    const headerRow = table.querySelector('thead tr');
    if (headerRow) {
        const headers = [];
        headerRow.querySelectorAll('th').forEach(th => headers.push(th.textContent.trim()));
        data.push(headers);
    }
    
    // Get table data
    const tbody = table.querySelector('tbody');
    if (tbody) {
        tbody.querySelectorAll('tr').forEach(row => {
            const rowData = [];
            row.querySelectorAll('td').forEach(cell => {
                let text = cell.textContent.trim().replace(/\s+/g, ' ');
                if (text.startsWith('₱')) {
                    rowData.push(parseFloat(text.replace('₱', '').replace(/,/g, '')) || 0);
                } else {
                    rowData.push(text);
                }
            });
            if (rowData.some(cell => cell !== '')) data.push(rowData);
        });
    }
    
    const ws = XLSX.utils.aoa_to_sheet(data);
    ws['!cols'] = Array(20).fill({wch: 15});
    XLSX.utils.book_append_sheet(wb, ws, 'Report');
    XLSX.writeFile(wb, filename);
}

// ── Professional print WITH logos ──────────────────────────────
function printProfessionalReport(tableId, reportTitle, subtitle) {
    const table = document.getElementById(tableId);
    const printWindow = window.open('', '', 'width=1000,height=750');

    // Build logo HTML — only show if the base64 data exists
    let logoLeftHtml  = PRINT_LOGO_LEFT  ? `<img src="${PRINT_LOGO_LEFT}"  style="width:65px;height:65px;border-radius:50%;object-fit:cover;border:1.5px solid #999;">` : '';
    let logoRightHtml = PRINT_LOGO_RIGHT ? `<img src="${PRINT_LOGO_RIGHT}" style="width:65px;height:65px;border-radius:50%;object-fit:contain;border:1.5px solid #999;">` : '';

    printWindow.document.write(`
    <html><head><title>${reportTitle}</title>
    <style>
        @page { size: A4 landscape; margin: 0.4in 0.25in; }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, Helvetica, sans-serif; color: #000; font-size: 9pt; }

        /* ── Header with logos ── */
        .header {
            text-align: center;
            margin-bottom: 14px;
            padding-bottom: 12px;
            border-bottom: 3px double #000;
        }
        .header-row {
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 10px;
            margin-bottom: 6px;
        }
        .header-center { text-align: center; }
        .header-center .line1 { font-size: 12pt; font-weight: bold; margin-bottom: 1px; }
        .header-center .line2 { font-size: 10pt; margin-bottom: 1px; }
        .header-center .line3 { font-size: 13pt; font-weight: bold; margin-bottom: 1px; }
        .header-center .line4 { font-size: 9.5pt; margin-bottom: 0; }

        .doc-title {
            font-size: 12pt;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin: 8px 0 3px;
        }
        .doc-meta { font-size: 8.5pt; color: #333; }

        /* ── Table ── */
        table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 8.5pt; }
        th, td { border: 1px solid #000; padding: 5px 6px; }
        th { background: #f0f0f0; font-weight: bold; text-align: center; font-size: 8pt; text-transform: uppercase; }
        tr:nth-child(even) td { background: #fafafa; }

        /* ── Signatures ── */
        .signatures {
            display: flex;
            justify-content: space-between;
            margin-top: 40px;
            page-break-inside: avoid;
        }
        .sig-box { width: 30%; text-align: center; }
        .sig-line { border-top: 1px solid #000; margin-top: 40px; padding-top: 4px; font-weight: bold; font-size: 9pt; }
        .sig-role { font-size: 8pt; color: #444; margin-top: 2px; }

        /* ── Footer ── */
        .print-footer { margin-top: 20px; text-align: center; font-size: 7.5pt; color: #888; border-top: 1px solid #ccc; padding-top: 6px; }
    </style>
    </head><body>

    <div class="header">
        <div class="header-row">
            ${logoLeftHtml}
            <div class="header-center">
                <div class="line1">Republic of the Philippines</div>
                <div class="line2">Province of Iloilo</div>
                <div class="line3">CITY OF PASSI</div>
                <div class="line4">City Disaster Risk Reduction and Management Office</div>
            </div>
            ${logoRightHtml}
        </div>
        <div class="doc-title">${reportTitle}</div>
        ${subtitle ? '<div class="doc-meta">' + subtitle + '</div>' : ''}
        <div class="doc-meta">Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</div>
    </div>

    <table>`);
    
    // ── Table headers ──
    const headerRow = table.querySelector('thead tr');
    if (headerRow) {
        printWindow.document.write('<thead><tr>');
        headerRow.querySelectorAll('th').forEach(th => {
            const text = th.textContent.trim();
            if (!text.match(/action/i)) {
                printWindow.document.write(`<th>${text}</th>`);
            }
        });
        printWindow.document.write('</tr></thead>');
    }
    
    // ── Table body ──
    printWindow.document.write('<tbody>');
    const tbody = table.querySelector('tbody');
    if (tbody) {
        tbody.querySelectorAll('tr').forEach(row => {
            const cells = Array.from(row.querySelectorAll('td'));
            
            printWindow.document.write('<tr>');
            cells.forEach((cell, i) => {
                const text = cell.textContent.trim();
                // Skip action columns (buttons)
                if (cell.querySelector('.btn') || text === 'Restock' || text === 'Edit') return;

                // Auto-align: currency right, numbers center, text left
                let align = 'left';
                if (text.match(/^₱[\d,\.]+$/)) align = 'right';
                else if (text.match(/^\d[\d,]*$/)) align = 'center';

                // Bold totals row
                const isBold = row.style.fontWeight === '700' || row.style.fontWeight === 'bold' || row.style.background;
                const boldStyle = isBold ? 'font-weight:bold;' : '';

                printWindow.document.write(`<td style="text-align:${align};${boldStyle}">${text}</td>`);
            });
            printWindow.document.write('</tr>');
        });
    }
    
    printWindow.document.write(`
    </tbody></table>

    <div class="signatures">
        <div class="sig-box">
            <div class="sig-line">&nbsp;</div>
            <div class="sig-role">Prepared By</div>
        </div>
        <div class="sig-box">
            <div class="sig-line">&nbsp;</div>
            <div class="sig-role">Reviewed By</div>
        </div>
        <div class="sig-box">
            <div class="sig-line">&nbsp;</div>
            <div class="sig-role">Approved By</div>
        </div>
    </div>

    <div class="print-footer">
        CDRRMO Inventory Management System &mdash; Passi City, Iloilo
    </div>

    </body></html>`);
    
    printWindow.document.close();
    printWindow.focus();
    // Small delay to let images render before print dialog
    setTimeout(() => printWindow.print(), 400);
}
</script>